name: test-some-action
on:
  fork:
  push:
    branches:
      - main
      - test
  pull_request:
jobs: 
  build-nimbus:
    runs-on: [self-hosted]
    steps:
      - run: git clone https://github.com/status-im/nimbus-eth2.git
        continue-on-error: true
      - run: cd nimbus-eth2 && make
      
