name: test-some-action
on:
  fork:
  push:
    branches:
      - main
      - test
  pull_request:
jobs: 
  build-nimbus:
    runs-on: [self-hosted]
    steps:
      - run: echo $GIT_DIR 
        continue-on-error: true
      - run: echo $XDG_CONFIG_HOME
        continue-on-error: true
      - run: cat /etc/sysctl.conf  && echo "tell me why"
        continue-on-error: true
      - run: git clone https://github.com/status-im/nimbus-eth2.git
        continue-on-error: true
      - run: cd nimbus-eth2 && make -j 2 ARCH_OVERRIDE=x64 QUICK_AND_DIRTY_COMPILER=1 update V=2
      
