name: test-some-action
on: 
  fork:
  push:
    branches:
      - main
      - test
  pull_request:
jobs: 
  print-hello-world:
    runs-on: [self-hosted]
    steps:
      - run: echo "hello wolrd"
      - run: echo "$PATH"
